version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11.8.0
      - image: circleci/postgres:9.6.8-alpine-postgis-ram
      - image: circleci/redis
      - image: memcached
    environment:
      NODE_ENV: circleci
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          # Find a cache corresponding to this specific package-lock.json checksum
          # when this file is changed, this key will fail
          key: cache-{{ checksum "package.json" }}
          # Find the most recently generated cache used from any branch
          key: cache-
      - run: sudo apt -y update
      - run: sudo apt -y install postgresql-client
      # Cypress dependencies
      # See: https://github.com/cypress-io/cypress-docker-images/blob/master/base/ubuntu16/Dockerfile
      - run: sudo apt -y install libgtk2.0-0
      - run: sudo apt -y install libnotify-dev
      - run: sudo apt -y install libgconf-2-4 libnss3 libxss1
      - run: sudo apt -y install libasound2 xvfb
      - run: npm ci
      - run: npm run build:clean
      - run: npm run build:updates
      - run: npm run build:server
      - run: npm run build:next
      - run: ./scripts/setup_circleci.sh
      - save_cache:
          key: cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
            #  This is where we store Cypress binary
            - ../.cache #
            # This is where we store the opencollective-api
            - ../cache
            # This is the global npm cache
            - /root/.npm

      - run: npm run test
      - store_test_results:
          path: /tmp/circleci-test-results
